### PR TITLE
Making changes to move this to fedora 28 compatibility

### PR DESCRIPTION
**Pull request by BunnyApocalypse**
Don't know what you wanted me to do about the broken NFS stuff so I just commented it out.

I changed the order of stuff in the system task because otherwise we were running into errors, not sure if that breaks any intended usecases but hopefully it doesnt

I also removed a few packages that no longer exist and also made some minor changes elsewhere to either update syntax or grammar.

The NFS issue would probably be related to [this issue with ansible ](https://github.com/cohoe/workstation/issues/22)

### CODE REVIEW

**Comment by rohitmusti** [comment]
This is a currently a problem with Fedora 28 Server, when trying to open the firewall for DNS I got the error: 

NameError: global name 'fw_offline' is not defined

**Comment by jdoss** [comment]
@rohitmusti this playbook is for usage on Fedora Workstation. If you are having issues with the firewall module, update to [ansible-2.5.5-2.fc28](https://koji.fedoraproject.org/koji/buildinfo?buildID=1092406)+ and it should fix the problem.

**Comment by rohitmusti** [comment]
I'm on 2.5.2, is this still an issue for even this version? I just ran my dnf update and am still running into the issue.

**Comment by jdoss** [comment]
You will need to install it from updates-testing or manually:

`dnf update https://kojipkgs.fedoraproject.org//packages/ansible/2.5.5/2.fc28/noarch/ansible-2.5.5-2.fc28.noarch.rpm`

**Pull request merged**
